package com.cgy.hupu.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.cgy.hupu.db.Forum;
import com.cgy.hupu.db.ReadThread;
import com.cgy.hupu.db.Thread;
import com.cgy.hupu.db.User;

import com.cgy.hupu.db.ForumDao;
import com.cgy.hupu.db.ReadThreadDao;
import com.cgy.hupu.db.ThreadDao;
import com.cgy.hupu.db.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig forumDaoConfig;
    private final DaoConfig readThreadDaoConfig;
    private final DaoConfig threadDaoConfig;
    private final DaoConfig userDaoConfig;

    private final ForumDao forumDao;
    private final ReadThreadDao readThreadDao;
    private final ThreadDao threadDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        forumDaoConfig = daoConfigMap.get(ForumDao.class).clone();
        forumDaoConfig.initIdentityScope(type);

        readThreadDaoConfig = daoConfigMap.get(ReadThreadDao.class).clone();
        readThreadDaoConfig.initIdentityScope(type);

        threadDaoConfig = daoConfigMap.get(ThreadDao.class).clone();
        threadDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        forumDao = new ForumDao(forumDaoConfig, this);
        readThreadDao = new ReadThreadDao(readThreadDaoConfig, this);
        threadDao = new ThreadDao(threadDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Forum.class, forumDao);
        registerDao(ReadThread.class, readThreadDao);
        registerDao(Thread.class, threadDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        forumDaoConfig.clearIdentityScope();
        readThreadDaoConfig.clearIdentityScope();
        threadDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public ForumDao getForumDao() {
        return forumDao;
    }

    public ReadThreadDao getReadThreadDao() {
        return readThreadDao;
    }

    public ThreadDao getThreadDao() {
        return threadDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
