package com.cgy.hupu.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.cgy.hupu.db.User;
import com.cgy.hupu.db.Forum;
import com.cgy.hupu.db.Thread;

import com.cgy.hupu.db.UserDao;
import com.cgy.hupu.db.ForumDao;
import com.cgy.hupu.db.ThreadDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig forumDaoConfig;
    private final DaoConfig threadDaoConfig;

    private final UserDao userDao;
    private final ForumDao forumDao;
    private final ThreadDao threadDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        forumDaoConfig = daoConfigMap.get(ForumDao.class).clone();
        forumDaoConfig.initIdentityScope(type);

        threadDaoConfig = daoConfigMap.get(ThreadDao.class).clone();
        threadDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        forumDao = new ForumDao(forumDaoConfig, this);
        threadDao = new ThreadDao(threadDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Forum.class, forumDao);
        registerDao(Thread.class, threadDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        forumDaoConfig.clearIdentityScope();
        threadDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public ForumDao getForumDao() {
        return forumDao;
    }

    public ThreadDao getThreadDao() {
        return threadDao;
    }

}
