package com.cgy.hupu.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.cgy.hupu.db.Forum;
import com.cgy.hupu.db.User;
import com.cgy.hupu.db.Thread;
import com.cgy.hupu.db.ReadThread;

import com.cgy.hupu.db.ForumDao;
import com.cgy.hupu.db.UserDao;
import com.cgy.hupu.db.ThreadDao;
import com.cgy.hupu.db.ReadThreadDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig forumDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig threadDaoConfig;
    private final DaoConfig readThreadDaoConfig;

    private final ForumDao forumDao;
    private final UserDao userDao;
    private final ThreadDao threadDao;
    private final ReadThreadDao readThreadDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        forumDaoConfig = daoConfigMap.get(ForumDao.class).clone();
        forumDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        threadDaoConfig = daoConfigMap.get(ThreadDao.class).clone();
        threadDaoConfig.initIdentityScope(type);

        readThreadDaoConfig = daoConfigMap.get(ReadThreadDao.class).clone();
        readThreadDaoConfig.initIdentityScope(type);

        forumDao = new ForumDao(forumDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        threadDao = new ThreadDao(threadDaoConfig, this);
        readThreadDao = new ReadThreadDao(readThreadDaoConfig, this);

        registerDao(Forum.class, forumDao);
        registerDao(User.class, userDao);
        registerDao(Thread.class, threadDao);
        registerDao(ReadThread.class, readThreadDao);
    }
    
    public void clear() {
        forumDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
        threadDaoConfig.getIdentityScope().clear();
        readThreadDaoConfig.getIdentityScope().clear();
    }

    public ForumDao getForumDao() {
        return forumDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public ThreadDao getThreadDao() {
        return threadDao;
    }

    public ReadThreadDao getReadThreadDao() {
        return readThreadDao;
    }

}
