package com.cgy.hupu.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Unique;

/**
 * Entity mapped to table USER.
 */
@Entity
public class User {

    @Id(autoincrement = true)
    private Long id;
    @Unique
    private String userName;
    private String uid;
    private String token;
    private String icon;
    private Integer sex;
    private String cookie;
    private String registerTime;
    private String location;
    private String school;
    private String threadUrl;
    private String postUrl;
    private String nickNameUrl;

    @Generated(hash = 1088311397)
    public User(Long id, String userName, String uid, String token, String icon, Integer sex,
                String cookie, String registerTime, String location, String school, String threadUrl,
                String postUrl, String nickNameUrl) {
        this.id = id;
        this.userName = userName;
        this.uid = uid;
        this.token = token;
        this.icon = icon;
        this.sex = sex;
        this.cookie = cookie;
        this.registerTime = registerTime;
        this.location = location;
        this.school = school;
        this.threadUrl = threadUrl;
        this.postUrl = postUrl;
        this.nickNameUrl = nickNameUrl;
    }

    @Generated(hash = 586692638)
    public User() {
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUid() {
        return this.uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getToken() {
        return this.token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getIcon() {
        return this.icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public Integer getSex() {
        return this.sex;
    }

    public void setSex(Integer sex) {
        this.sex = sex;
    }

    public String getCookie() {
        return this.cookie;
    }

    public void setCookie(String cookie) {
        this.cookie = cookie;
    }

    public String getRegisterTime() {
        return this.registerTime;
    }

    public void setRegisterTime(String registerTime) {
        this.registerTime = registerTime;
    }

    public String getLocation() {
        return this.location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getSchool() {
        return this.school;
    }

    public void setSchool(String school) {
        this.school = school;
    }

    public String getThreadUrl() {
        return this.threadUrl;
    }

    public void setThreadUrl(String threadUrl) {
        this.threadUrl = threadUrl;
    }

    public String getPostUrl() {
        return this.postUrl;
    }

    public void setPostUrl(String postUrl) {
        this.postUrl = postUrl;
    }

    public String getNickNameUrl() {
        return this.nickNameUrl;
    }

    public void setNickNameUrl(String nickNameUrl) {
        this.nickNameUrl = nickNameUrl;
    }

}
